name = "aeron-x"
main = "src/worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "npm run build"

# Uncomment and configure KV namespace after creating it in Cloudflare Dashboard
# [[kv_namespaces]]
# binding = "ASSETS"
# preview_id = "your-preview-namespace-id"
# id = "your-production-namespace-id"

[vars]
ENVIRONMENT = "production" 