name = "aeronxhome"
compatibility_date = "2024-01-15"

[site]
bucket = "./dist"

[build]
command = "npm install && npm run build"
output_dir = "dist"

[env.production]
name = "aeronxhome"

[[pages_build_output_dir]]
value = "dist"
