name = "aeron-x-flowscape-website"
compatibility_date = "2024-01-15"

[site]
bucket = "./dist"

[build]
command = "npm run build"
output_dir = "dist"

[env.production]
name = "aeron-x-flowscape-website"

[[pages_build_output_dir]]
value = "dist"
