name = "aeron-x"
main = "src/worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "ASSETS"
preview_id = ""
id = ""

[vars]
ENVIRONMENT = "production" 